/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/App.js",
    "./src/components/accordian/index.jsx", 
    "./src/components/random_color/index.jsx",
    "./src/components/star_rating/index.jsx",
    "./src/components/image_slider/index.jsx",
    "./src/components/load-more-data/index.jsx", 
    "./src/components/tree-view/index.jsx",
    "./src/components/tree-view/menu_list.jsx",
    "./src/components/tree-view/menu-item.jsx",
    "./src/components/qrcode/index.jsx",
    "./src/components/light_dark_mode/index.jsx",
    "./src/components/custom_scroll_indicator/index.jsx",
    "./src/components/custom-tabs/tabs.jsx",
    "./src/components/custom-tabs/tabs-test.jsx",
    "./src/components/custom_modal_popup/modal-test.jsx",
    "./src/components/custom_modal_popup/modal.jsx",
    "./src/components/github_profile_finder/index.jsx",
    "./src/components/github_profile_finder/user_card.jsx",
    "./src/components/search-autocomplete/index.jsx",
    "./src/components/search-autocomplete/suggestoins.jsx",
    "./src/components/feature-flag/index.jsx",
    "./src/components/feature-flag/context/index.jsx",
    "./src/components/useFetch/test.jsx",
    "./src/components/clickOutside/test.jsx",
    "./src/components/useWindowResize/test.jsx",
    "./src/components/ScrollTopBottom/index.jsx",
    "./src/components/ScrollSection/index.jsx"],
  theme: {
    extend: {},
  },
  plugins: [],
}

